stages:
    - build
    - deploy

variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:latest

build:
    stage: build
    tags:
        - privileged
    image: docker:stable
    services:
        - docker:dind
    variables:
        DOCKER_HOST: tcp://docker:2375/
        DOCKER_DRIVER: overlay2
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t $IMAGE_TAG .
        - docker push $IMAGE_TAG

deploy:
    stage: deploy
    image: alpine:latest
    variables:
        DEPLOY_HOST: henry4k.de
        DEPLOY_USER: live-share
    before_script:
        # Install ssh-agent if not already installed, it is required by Docker.
        - apk add --no-cache openssh-client

        # Run ssh-agent (inside the build environment)
        - eval $(ssh-agent -s)

        # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
        # We're using tr to fix line endings which makes ed25519 keys work
        # without extra base64 encoding.
        # https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

        # Create the SSH directory and give it the right permissions
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh

        - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts
    script:
        - ssh "$DEPLOY_USER@$DEPLOY_HOST" "sudo systemctl restart live-share.service"
