#!/bin/sh
for dep in lua-cjson \
           luadbi \
           luadbi-sqlite3 \
           mimetypes \
           cqueues \
           http \
           lua-path \
           middleclass \
           fat_error \
           luaposix; do
    echo "------------------- $dep ---------------------"
    luarocks-5.2 --local install $dep
done
