#!/bin/bash
set -e
for dep in lua-cjson \
           luadbi \
           luadbi-sqlite3 \
           mimetypes \
           cqueues \
           lpeg \
           lpeg_patterns \
           fifo \
           http \
           luaossl \
           compat53 \
           ansicolors \
           basexx \
           lua-path \
           middleclass \
           fat_error \
           luaposix; do
    echo "------------------- $dep ---------------------"
    luarocks-5.2 --local install $dep
done
