#!/bin/bash
set -e
for dep in argparse \
           lua-cjson \
           luadbi \
           luadbi-sqlite3 \
           mimetypes \
           cqueues \
           lpeg \
           lpeg_patterns \
           fifo \
           http \
           luaossl \
           compat53 \
           ansicolors \
           basexx \
           lua-path \
           middleclass \
           fat_error \
           luaposix; do
    echo "------------------- $dep ---------------------"
    luarocks-5.2 --local install $dep
done
luarocks-5.2 --local install argon2 ARGON2_INCDIR=/usr/include ARGON2_LIBDIR=/usr/lib
