include config.mk

.PHONY: build clean lint lint-lua lint-js lint-sh test install gh-pages

build: .gitignore src/web/dist
	tools/install-lua-deps \
		--lua-luarocks $(LUA_LUAROCKS) \
		--lua-tree $(LUA_TREE) \
		--luajit-luarocks $(LUAJIT_LUAROCKS) \
		--luajit-tree $(LUAJIT_TREE)

GENERATED_FILES += server
server:
	tools/generate-executable \
		--output $@ \
		--lib-dir src/lua \
		--data-dir _data_dir_missing_ \
		--lua $(LUA_HOST) \
		--package 'live-share.cli'

GENERATED_FILES += postprocess-image
postprocess-image: src/lua/live-share/postprocess-image.lua
	tools/generate-executable \
		--output $@ \
		--lib-dir src/lua \
		--data-dir _data_dir_missing_ \
		--lua $(LUAJIT_HOST) \
		--package 'live-share.postprocess-image'

GENERATED_FILES += src/web/dist
GENERATED_FILES += src/web/node_modules
src/web/dist:
	cd src/web && npm install
	cd src/web && npm run build

GENERATED_FILES += doc
doc:
	mkdir $@

ifneq ($(LDOC),)
doc/lua:src/lua/live-share config.ld
	$(LDOC) --dir $@ $<
endif

ifneq ($(APIDOC),)
doc/web: src/lua/live-share apidoc.json
	$(APIDOC) --input $< --output $@
endif

GENERATED_FILES += .gitignore
.gitignore:
	echo '# FILE IS GENERATED BY MAKE - DO NOT EDIT' > $@
	echo '/config.mk' >> $@
	for file in $(GENERATED_FILES) ; do \
		echo /$$file >> $@ ; \
	done

clean:
	rm -vr $(GENERATED_FILES)

lint: lint-lua lint-js lint-sh

ifneq ($(LUACHECK),)
lint-lua: src/lua
	$(LUACHECK) $^
else
lint-lua:
endif

lint-js:
	cd src/web && npm run lint

ifneq ($(CHECKBASHISMS),)
lint-sh: configure tools/utils.sh tools/install-lua-deps tools/show-test-coverage
	$(CHECKBASHISMS) --extra $^
else
lint-sh:
endif

ifneq ($(BUSTED),)
test:
	$(BUSTED) '--lua=$(LUA)' $@
endif

install:
	mkdir -p $(INSTALL_BIN_DIR)
	mkdir -p $(INSTALL_LIB_DIR)/lua
	mkdir -p $(INSTALL_DATA_DIR)/web
	cp -R -t $(INSTALL_LIB_DIR)/lua src/lua/*
	cp -R -t $(INSTALL_DATA_DIR)/web src/web/dist/*
	tools/generate-executable \
		--output $(INSTALL_BIN_DIR)/live-share-server \
		--lib-dir $(INSTALL_LIB_DIR) \
		--data-dir $(INSTALL_DATA_DIR) \
		--lua $(LUA_HOST) \
		--package 'live-share.cli'
	tools/generate-executable \
		--output $(INSTALL_LIB_DIR)/postprocess-image \
		--lib-dir $(INSTALL_LIB_DIR) \
		--data-dir $(INSTALL_DATA_DIR) \
		--lua $(LUAJIT_HOST) \
		--package 'live-share.postprocess-image'

gh-pages: doc
	tools/update-gh-pages $<
