#!/bin/bash
set -e
cd "$(dirname "$0")"
source utils.bash


function install-lua-package
{
    local lua_version="$1"
    local package="$2"
    shift 2
    echo "------------------- $package ---------------------"
    "luarocks-$lua_version" --local install "$package" $@
}

function install-lua-packages
{
    local lua_version="$1"
    shift 1
    for package in $@; do
        install-lua-package "$lua_version" "$package"
    done
}

install-lua-packages 5.2 argparse \
                         lua-cjson \
                         luadbi \
                         luadbi-sqlite3 \
                         mimetypes \
                         cqueues \
                         lpeg \
                         lpeg_patterns \
                         fifo \
                         http \
                         luaossl \
                         compat53 \
                         ansicolors \
                         basexx \
                         lua-path \
                         middleclass \
                         fat_error \
                         luaposix \
                         xcq-subprocess

install-lua-package 5.2 argon2 ARGON2_INCDIR=/usr/include ARGON2_LIBDIR=/usr/lib

install-lua-packages 5.1 lua-vips \
                         lua-cjson
