#!/bin/sh
set -e

here="$(dirname "$0")"
. "$here/utils.sh"

# Default values:
lua_tree=
luajit_tree=

while true; do
    case "$1" in
        --lua-luarocks)
            lua_luarocks="$2"
            shift 2
            ;;

        --lua-tree)
            lua_tree="$2"
            shift 2
            ;;

        --luajit-luarocks)
            luajit_luarocks="$2"
            shift 2
            ;;

        --luajit-tree)
            luajit_tree="$2"
            shift 2
            ;;

        *)
            break
            ;;
    esac
done

set -u

install_lua_package()
{
    local luarocks="$1"
    local tree="$2"
    local package="$3"
    shift 3

    if [ "$tree" = '' ]; then
        local tree_arg='--local'
    else
        local tree_arg="--tree $tree"
    fi

    echo "------------------- $package ---------------------"
    "$luarocks" $tree_arg install "$package" $@
}

install_lua_packages()
{
    local luarocks="$1"
    local tree="$2"
    shift 2
    for package in $@; do
        install_lua_package "$luarocks" "$tree" "$package"
    done
}

install_lua_packages "$lua_luarocks" "$lua_tree" \
    argparse \
    lua-cjson \
    luadbi \
    luadbi-sqlite3 \
    mimetypes \
    cqueues \
    lpeg \
    lpeg_patterns \
    fifo \
    http \
    luaossl \
    compat53 \
    ansicolors \
    basexx \
    lua-path \
    middleclass \
    fat_error \
    luaposix \
    xcq-subprocess

install_lua_package "$lua_luarocks" "$lua_tree" \
    argon2 ARGON2_INCDIR=/usr/include ARGON2_LIBDIR=/usr/lib

install_lua_packages "$luajit_luarocks" "$luajit_tree" \
    lua-vips \
    lua-cjson
