#!/bin/bash
BRANCH='gh-pages'
SOURCE_DIR="$1"
PROJECT_DIR="$(dirname "$0")/.."

set -e

function teardown()
{
    git worktree prune
}
trap teardown EXIT

git -C "$PROJECT_DIR" worktree add --force "$SOURCE_DIR" "$BRANCH"

git -C "$SOURCE_DIR" diff

read -p "Is this okay? " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

git -C "$SOURCE_DIR" commit --all --allow-empty-message -m ''
