#!/bin/sh
set -o errexit
set -o nounset

branch='gh-pages'
source_dir="$1"
project_dir="$(dirname "$0")/.."

function teardown()
{
    git worktree prune
}
trap teardown EXIT

git -C "$project_dir" worktree add --force "$source_dir" "$branch"

git -C "$source_dir" diff

read -p "Is this okay? y/n: " -n 1 -r
echo
if [ $REPLY != 'y' ]; then
    exit 1
fi

git -C "$source_dir" commit --all --allow-empty-message -m ''
